# Generated by Django 6.0.3 on 2026-03-28 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_owner', models.CharField(max_length=255)),
                ('original_repo', models.CharField(max_length=255)),
                ('imported_repo_name', models.CharField(max_length=255)),
                ('imported_repo_url', models.URLField()),
                ('customizations_applied', models.JSONField(default=list)),
                ('status', models.CharField(default='success', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
